/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface1: 'var(--surface-1)',
        surface2: 'var(--surface-2)',
        textPrimary: 'var(--text-primary)',
        textSecondary: 'var(--text-secondary)',
        textMuted: 'var(--text-muted)',
        border: 'var(--border)',
        accent: 'var(--fill-accent)',
        onAccent: 'var(--on-accent)',
        bgAccent: 'var(--bg-accent)',
        textAccent: 'var(--text-accent)',
        success: 'var(--text-success)',
        danger: 'var(--text-danger)',
        warning: 'var(--text-warning)',
        info: 'var(--text-info)',
        bgSuccess: 'var(--bg-success)',
        bgDanger: 'var(--bg-danger)',
        bgWarning: 'var(--bg-warning)',
        bgInfo: 'var(--bg-info)',
        brand: 'var(--fill-accent)',
        bgSecondary: 'var(--surface-1)',
        surface3: 'var(--surface-3)',
        nav: 'var(--nav-bg)',
        navBorder: 'var(--nav-border)',
        navText: 'var(--nav-text)',
        navTextHover: 'var(--nav-text-hover)',
        navHover: 'var(--nav-hover-bg)',
        navActive: 'var(--nav-active-bg)',
        dropdownBg: 'var(--dropdown-bg)',
        financial: 'var(--fill-financial)',
        onFinancial: 'var(--on-financial)',
        textFinancial: 'var(--text-financial)',
        voucherPayment: 'var(--voucher-payment)',
        voucherReceipt: 'var(--voucher-receipt)',
        voucherJournal: 'var(--voucher-journal)',
        voucherKachi: 'var(--voucher-kachi)',
        metricCashBg: 'var(--metric-cash-bg)',
        metricCashAccent: 'var(--metric-cash-accent)',
        metricReceivablesBg: 'var(--metric-receivables-bg)',
        metricReceivablesAccent: 'var(--metric-receivables-accent)',
        metricPayablesBg: 'var(--metric-payables-bg)',
        metricPayablesAccent: 'var(--metric-payables-accent)',
        metricVouchersBg: 'var(--metric-vouchers-bg)',
        metricVouchersAccent: 'var(--metric-vouchers-accent)',
        cardSaleCommissionBg: 'var(--card-sale-commission-bg)',
        cardSaleCommissionAccent: 'var(--card-sale-commission-accent)',
        cardSalePaunchBg: 'var(--card-sale-paunch-bg)',
        cardSalePaunchAccent: 'var(--card-sale-paunch-accent)',
        cardPurchaseMaalBg: 'var(--card-purchase-maal-bg)',
        cardPurchaseMaalAccent: 'var(--card-purchase-maal-accent)',
        cardKachiMaalBg: 'var(--card-kachi-maal-bg)',
        cardKachiMaalAccent: 'var(--card-kachi-maal-accent)',
        cardInvoiceHistoryBg: 'var(--card-invoice-history-bg)',
        cardInvoiceHistoryAccent: 'var(--card-invoice-history-accent)',
      },
    },
  },
  plugins: [],
};
