import {
  BarChart3,
  Boxes,
  CircleDollarSign,
  CircleUser,
  ClipboardList,
  CreditCard,
  FileText,
  HandCoins,
  Landmark,
  Package,
  PlusCircle,
  Receipt,
  RotateCcw,
  Scale,
  ScanBarcode,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Truck,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

/** Top-level nav group icons (gold/black sidebar identity preserved in top bar). */
export const NAV_GROUP_ICONS: Record<string, LucideIcon> = {
  Sales: ShoppingCart,
  Customers: CircleUser,
  Products: Package,
  Suppliers: Truck,
  Finance: Wallet,
  Accounts: CreditCard,
  Voucher: Receipt,
  Reports: BarChart3,
  System: Settings,
  User: CircleUser,
};

/** Common nav link / hub action icons by label. */
export const NAV_LINK_ICONS: Record<string, LucideIcon> = {
  'New Sale': ShoppingCart,
  'Recent Invoices': FileText,
  'Return / Exchange': RotateCcw,
  'Customer List': CircleUser,
  'Add Customer': PlusCircle,
  'Receive Payment': HandCoins,
  'Product List': Package,
  'Add Product': PlusCircle,
  'Scan barcode': ScanBarcode,
  'Supplier List': Truck,
  'Add Supplier': PlusCircle,
  'New Purchase': ShoppingBag,
  Purchases: ClipboardList,
  'Pay Supplier': Wallet,
  'Record Expense': Wallet,
  'Add Expense': Wallet,
  'Expense List': FileText,
  'Expense History': FileText,
  'Record Other Income': HandCoins,
  'Add Other Income': CircleDollarSign,
  'Other Income History': FileText,
  'Finance Overview': Landmark,
  'Add E-payment methods': Smartphone,
  Settings: Settings,
  'System Health': ShieldCheck,
  'Daily Sales': BarChart3,
  'Sales Range': BarChart3,
  'Low Stock': Boxes,
  'Out of Stock': Boxes,
  'Current Stock': Boxes,
  'Customer Balances': HandCoins,
  'Trial Balance': Scale,
};

export function navLinkIcon(label: string): LucideIcon | null {
  return NAV_LINK_ICONS[label] ?? null;
}
